### ISSUE TITLE
Sidebar: при hasOverlay:false клики не всплывают за окно

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2056]
```css
.Sidebar:not(.Sidebar_hasOverlay) {
    pointer-events: none;
}
```
