### ISSUE TITLE
AgGridAdapter: тематизация иконок

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#2238]
```css
& .ag-icon-tree-closed {
    width: var(--space-m);
    height: var(--space-m);

    background-image: url('data:image/svg+xml;base64,PHN2ZyB3a...');
  }
```

препарировать иконку в http://base64.ru/
вырезать цвет размеры маски, 

пример препарированной иконки
```html
<svg viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg">
    <path d="M4 12L8 12L8 0L4 0L4 12ZM-1 12H3L3 0L-1 0L-1 12ZM9 0L9 12H13L13 0L9 0Z"/>
</svg>
```

```css
& .ag-icon-tree-closed {
    width: var(--space-m);
    height: var(--space-m);

   mask-image: url('data:image/svg+xml;base64,PHN2ZyB3a...');
   background: var(--need-color); 
  }
```
