### ISSUE TITLE
Image: изображение в качестве плейсхолдера

### ISSUE THREAD

**Issue by monolithed** [consta-design-system/uikit#3358]
Предлагаю добавить фичу, которая присутствует практически на всех приличных сайтах —  плейсхолдер для загружаемых картинок. 
Генерировать сами плейсхолдеры (картинки с blur-эффектом) не предлагаю.

<img width="669" alt="Screenshot 2023-10-17 at 23 29 13" src="https://github.com/consta-design-system/uikit/assets/803674/8b60aeb3-bc5a-4ed1-87e9-a0e520e748c6">

**Кейсы:**

1. Изображение еще не загружено
2. До изображения еще не проскроллено
3. Изображения пока скрыто (например, табы)
4. Скрывать заглушку через n-секунд после срабатывания onload
5. Плейсхолдер должен наследовать стили от целевого изображения
6. Если плейсхолдера нет — показывать серую заливку
7. Компонент должен учитывать динамичность изображений (width и height следует сделать опциональными)
8. Поддержать SSR?

Пример реализации можно подсмотреть в Next, они покрывают все эти кейсы или тут [react-lazy-load-image-component](react-lazy-load-image-component) (хоть это и не лучший пример реализации)

**Пример использования:**

В тег Image добавляется атрибут placeholder c указанием на путь к изображению или `data:строка`.

```jsx
<Image placeholder="data:svg..." />
<Image placeholder="/placeholder.svg" />
<Image placeholder{<img src="/placeholder.svg"}} />
```

**Описание реализации:**

Рядом с изображением, которое должно показаться пользователю добавляется изображение с заглушкой. По событию onload вместо заглушки показываем целевое изображение.

**Примерные стили для плейсхолдера:**

```css
.wrapper {
    display: block;
    position: relative;
}

.placeholder {
    position: absolute;
    height: 100%;
    width: 100%;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    background-size: cover;
    background-position: 50% 50%;
    background-repeat: no-repeat;
}

.image {
    overflow: hidden;
    display: block;
    position: relative;
    object-fit: cover;
    object-position: center;
    width: 100%;
    height: 100%;
}
```
 
**О готовом:**

1. [Реализация](https://nextjs.org/docs/pages/building-your-application/optimizing/images) в Next хоть и корректная, но она привязана к их компоненту Image с [кривым](https://github.com/vercel/next.js/issues/54371) srcSet.
2.  [react-lazy-load-image-component](react-lazy-load-image-component) - его реализация не покрывает кейс `#3`, а `#2` работает c жуткими багами - скрывает плейсхолдер раньше чем загрузится изображение.
3. [laziest-image](https://github.com/ilvetrov/laziest-image) не смог завести, заброшена

**Как генерировать плейсхолдеры:**

1. Есть относительно готовое решение [svg-blur-up](https://github.com/vanruesc/blur-up), 
2. [На затравку](https://jmperezperez.com/blog/svg-placeholders/)
