### ISSUE TITLE
Text: добавить недостающие значения для _weight

### ISSUE THREAD

**Issue by gizeasy** [consta-design-system/uikit#3765]
##TIME=1:30##

у нас есть в теме есть 9 значений для ширины текста

```css
  --font-weight-text-thin: 100;
  --font-weight-text-extralight: 200;
  --font-weight-text-light: 300;
  --font-weight-text-regular: normal;
  --font-weight-text-medium: 500;
  --font-weight-text-semibold: 600;
  --font-weight-text-bold: bold;
  --font-weight-text-extrabold: 800;
  --font-weight-text-black: 900;
```

а в компоненте Text можно использовать только 7

```css
&_thin {
  font-weight: var(--font-weight-text-thin);
}

&_light {
  font-weight: var(--font-weight-text-light);
}

&_regular {
  font-weight: var(--font-weight-text-regular);
}

&_medium {
  font-weight: var(--font-weight-text-medium);
}

&_semibold {
  font-weight: var(--font-weight-text-semibold);
}

&_bold {
  font-weight: var(--font-weight-text-bold);
}

&_black {
  font-weight: var(--font-weight-text-black);
}
```
